import type { Model } from './model';
import { modelId } from '../ids';

// One model per tier so dispatcher routing scenarios can be exercised end-to-end.
// Slugs follow OpenRouter convention (`provider/model-name`) — the same string the
// upstream router accepts, no translation layer.

export const MODELS = [
  {
    id: modelId('local/qwen2.5:7b'),
    display_name: 'Qwen 2.5 (7B, local)',
    provider: 'meta',
    tier: 'free',
    capabilities: ['text'],
    context_window: 32_000,
    input_cost_per_mtok: 0,
    output_cost_per_mtok: 0,
    is_active: true,
    notes: 'Local on 24GB RAM via Ollama. Used by ralph for free-tier work.',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
  {
    id: modelId('anthropic/claude-haiku-4-5'),
    display_name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    tier: 'budget',
    capabilities: ['text', 'code', 'vision'],
    context_window: 200_000,
    input_cost_per_mtok: 0.80,
    output_cost_per_mtok: 4.00,
    is_active: true,
    notes: 'Budget tier default for boris.',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
  {
    id: modelId('anthropic/claude-sonnet-4-6'),
    display_name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    tier: 'standard',
    capabilities: ['text', 'code', 'vision', 'reasoning'],
    context_window: 200_000,
    input_cost_per_mtok: 3.00,
    output_cost_per_mtok: 15.00,
    is_active: true,
    notes: 'Standard tier; Sonnet-class anchor for skill model_hint=standard.',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
  {
    id: modelId('anthropic/claude-opus-4-7'),
    display_name: 'Claude Opus 4.7',
    provider: 'anthropic',
    tier: 'premium',
    capabilities: ['text', 'code', 'vision', 'reasoning', 'math'],
    context_window: 200_000,
    input_cost_per_mtok: 15.00,
    output_cost_per_mtok: 75.00,
    is_active: true,
    notes: 'Premium tier; reserved for hardest reasoning passes.',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
  {
    id: modelId('openai/gpt-5-nano'),
    display_name: 'GPT-5 nano',
    provider: 'openai',
    tier: 'budget',
    capabilities: ['text', 'code'],
    context_window: 128_000,
    input_cost_per_mtok: 0.50,
    output_cost_per_mtok: 2.00,
    is_active: true,
    notes: 'Alternate budget option; useful when Anthropic rate-limits.',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
] as const satisfies readonly Model[];
