import {
  Archive,
  Bot,
  Check,
  ChevronsDown,
  Clock,
  Dumbbell,
  ExternalLink,
  Github,
  GitBranch,
  GripVertical,
  History,
  Inbox,
  Keyboard,
  ListChecks,
  LogOut,
  MessageSquare,
  Newspaper,
  Pencil,
  Plus,
  RotateCcw,
  ScanBarcode,
  Search,
  Sunrise,
  Timer,
  Trash2,
  UtensilsCrossed,
  X,
  type LucideIconData,
} from 'lucide-angular';

// Semantic names (not lucide names) so the underlying icon can be swapped without
// touching call sites. Keep this list curated — only add what we actually use.
export const ICONS = {
  edit:           Pencil,
  delete:         Trash2,
  add:            Plus,
  clock:          Clock,
  'external-link': ExternalLink,
  'grip-vertical': GripVertical,
  approve:        Check,
  reject:         X,
  archive:        Archive,
  answer:         MessageSquare,
  decompose:      GitBranch,
  retry:          RotateCcw,
  demote:         ChevronsDown,
  'mark-done':    Check,
  github:         Github,
  search:         Search,
  'sign-out':     LogOut,
  today:          Sunrise,
  food:           UtensilsCrossed,
  gym:            Dumbbell,
  // Home-screen launcher tiles.
  focus:          Timer,
  scan:           ScanBarcode,
  capture:        Keyboard,
  replay:         History,
  fleet:          Bot,
  briefing:       Newspaper,
  'close-day':    ListChecks,
  inbox:          Inbox,
} as const satisfies Record<string, LucideIconData>;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES: readonly IconName[] = Object.keys(ICONS) as IconName[];
